StackName: shiny-app-power-analysis
 
TemplateBody: 
  Fn::Stringify: !Include ../cfn-template-continuous-integration/ecs.yml 
 
Capabilities: 
      - CAPABILITY_IAM 
 
Parameters: 
  - ParameterKey: ServiceStackName 
    ParameterValue: shiny-app-power-analysis-service
  - ParameterKey: ClusterName 
    ParameterValue: shiny-service-Cluster-13K1HOEQE9A45 
  - ParameterKey: ComputeType 
    ParameterValue: BUILD_GENERAL1_SMALL 
  - ParameterKey: BuildNotificationTopic 
    ParameterValue: arn:aws:sns:us-east-1:833333815239:shiny-alerts-Topic-19V4VT9HQ61ZN 